In [27]:
import numpy as np


class HistogramFilter(object):
    """
    Class HistogramFilter implements the Bayes Filter on a discretized grid space.
    """

    def histogram_filter(self, cmap, belief, action, observation):
        '''
        Takes in a prior belief distribution, a colormap, action, and observation, and returns the posterior
        belief distribution according to the Bayes Filter.
        :param cmap: The binary NxM colormap known to the robot.
        :param belief: An NxM numpy ndarray representing the prior belief.
        :param action: The action as a numpy ndarray. [(1, 0), (-1, 0), (0, 1), (0, -1)]
        :param observation: The observation from the color sensor. [0 or 1].
        :return: The posterior distribution.
        '''

        ### Your Algorithm goes Below.
        
        def predict(belief_P,action):
            result = np.zeros(belief_P.shape)
            for i in range(belief_P.shape[0]):
                for j in range(belief_P.shape[1]):
                    if(action[0] == 1):
                        if(((i + 1 )< (belief_P.shape[0])) and ((i + 1) > -1)):
                            result[i][j] += (0.1*belief_P[i][j])
                            result[i+1][j] += (0.9*belief_P[i][j])
                        else:
                            result[i][j] += belief_P[i][j]

                    if(action[0] == -1):
                        if(((i - 1 )< (belief_P.shape[0])) and ((i - 1) > -1)):
                            result[i][j] += (0.1*belief_P[i][j])
                            result[i-1][j] += 0.9*belief_P[i][j]
                        else:
                            result[i][j] += belief_P[i][j]

                    if(action[1] == 1):        
                        if(((j + 1 )< (belief_P.shape[1])) and ((j + 1) > -1)):
                            result[i][j] += (0.1*belief_P[i][j])
                            result[i][j+1] += (0.9*belief_P[i][j])
                        else:
                            result[i][j] += belief_P[i][j]

                    if(action[1] == -1):
                        if(((j - 1 )< (belief_P.shape[1])) and ((j - 1) > -1)):
                            result[i][j] += (0.1*belief_P[i][j])
                            result[i][j-1] += (0.9*belief_P[i][j]) 
                        else:
                            result[i][j] += belief_P[i][j]

            return result

        def update(belief_U,observation,cmap):
            result_U = np.zeros(belief_U.shape)
            for i in range(cmap.shape[0]):
                for j in range(cmap.shape[1]):
                    if(cmap[i][j] == observation):
                        result_U[i][j] = belief_U[i][j]*0.9
                    else:
                        result_U[i][j] = belief_U[i][j]*0.1
            result_U = result_U/np.sum(result_U)
            
            return result_U
        ans = belief
        for i in range(len(observation)):
            p = predict(ans,action[i])
            ans = update(p,observation[i],cmap)
            print(np.unravel_index(np.argmax(ans),belief.shape))
            
        return ans
        

In [28]:
import numpy as np
import matplotlib.pyplot as plt
##import HistogramFilter
import random
if __name__ == "__main__":

    # Load the data
    data = np.load(open('starter.npz', 'rb'))
    cmap = data['arr_0']
    actions = data['arr_1']
    observations = data['arr_2']
    belief_states = data['arr_3']

    #print("belief_states: \n", belief_states)
    #print(belief_states.shape)
    
    
    
    belief = np.full((cmap.shape),1/(cmap.shape[0]*cmap.shape[1]))
    #print(belief)
    H = HistogramFilter()
    answer = H.histogram_filter(cmap, belief, actions, observations)
    
    #### Test your code here


(19, 0)
(19, 0)
(19, 7)
(19, 11)
(18, 11)
(17, 11)
(17, 12)
(17, 11)
(18, 11)
(19, 11)
(6, 2)
(12, 2)
(12, 1)
(11, 1)
(7, 14)
(8, 14)
(4, 14)
(4, 13)
(4, 14)
(4, 13)
(12, 2)
(4, 15)
(10, 4)
(8, 15)
(7, 15)
(7, 16)
(7, 17)
(7, 17)
(7, 16)
(7, 17)


In [29]:
np.amax(answer)

0.23047559176435964

In [30]:
np.unravel_index(np.argmax(answer),belief.shape)

(7, 17)

In [31]:
belief_states

array([[19, 19],
       [19, 16],
       [14, 19],
       [ 7,  7],
       [ 6,  7],
       [ 5,  7],
       [ 3,  6],
       [ 3,  5],
       [ 4,  5],
       [ 5,  5],
       [ 6,  5],
       [ 6,  6],
       [ 6,  6],
       [ 5,  6],
       [ 3,  2],
       [ 4,  2],
       [ 4,  2],
       [ 6,  6],
       [ 6,  7],
       [ 6,  6],
       [ 6,  7],
       [ 4,  3],
       [ 5,  3],
       [ 6,  3],
       [ 5,  3],
       [ 5,  4],
       [ 5,  5],
       [ 5,  6],
       [ 5,  5],
       [ 5,  6]], dtype=int64)

In [19]:
cmap

array([[1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0],
       [1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1],
       [1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1],
       [1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0],
       [0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0],
       [0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0],
       [1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1],
       [1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1],
       [1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1],
       [1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1],
       [1, 0, 1, 0, 0, 1, 0, 0, 1,

In [20]:
cmap[5][6]

1

In [21]:
observations

array([0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [22]:
belief[19][16]

0.0025

In [23]:
actions[0][0]

1

In [24]:
answer

array([[4.42043222e-04, 4.91159136e-04, 4.42043222e-03, 4.91159136e-04,
        4.42043222e-03, 4.42043222e-03, 4.42043222e-03, 4.42043222e-03,
        4.42043222e-03, 4.42043222e-03, 4.42043222e-03, 4.42043222e-03,
        4.91159136e-04, 4.91159136e-04, 4.42043222e-03, 4.91159136e-04,
        4.42043222e-03, 4.91159136e-04, 4.42043222e-03, 9.33202358e-04],
       [4.91159136e-05, 4.42043222e-03, 4.91159136e-04, 4.91159136e-04,
        4.42043222e-03, 4.42043222e-03, 4.91159136e-04, 4.42043222e-03,
        4.91159136e-04, 4.42043222e-03, 4.42043222e-03, 4.42043222e-03,
        4.42043222e-03, 4.91159136e-04, 4.42043222e-03, 4.42043222e-03,
        4.91159136e-04, 4.42043222e-03, 4.42043222e-03, 9.33202358e-04],
       [4.42043222e-04, 4.91159136e-04, 4.91159136e-04, 4.91159136e-04,
        4.91159136e-04, 4.42043222e-03, 4.42043222e-03, 4.91159136e-04,
        4.42043222e-03, 4.91159136e-04, 4.91159136e-04, 4.42043222e-03,
        4.91159136e-04, 4.91159136e-04, 4.42043222e-03, 4.9115

In [22]:
actions

array([[ 1,  0],
       [ 1,  0],
       [ 1,  0],
       [ 0, -1],
       [-1,  0],
       [-1,  0],
       [ 0,  1],
       [ 0, -1],
       [ 1,  0],
       [ 1,  0],
       [ 1,  0],
       [ 0,  1],
       [ 0, -1],
       [-1,  0],
       [ 0,  1],
       [ 1,  0],
       [ 0,  1],
       [ 0, -1],
       [ 0,  1],
       [ 0, -1],
       [ 0,  1],
       [ 0,  1],
       [ 1,  0],
       [ 1,  0],
       [-1,  0],
       [ 0,  1],
       [ 0,  1],
       [ 0,  1],
       [ 0, -1],
       [ 0,  1]], dtype=int64)